pull_request_rules: []
queue_rules:
  - name: default
    queue_conditions: []
    merge_conditions:
      - check-success = @github-actions/vm6-extends-delay
    merge_method: merge
    checks_timeout: null
